# Site settings
title: Cheap Appliance Repair
email: ask@cheaprepair.link
url: https://www.cheaprepair.link
description: "Cheapest appliance diagnostics in Ottawa. Quick, reliable fixes and no hidden services. Save big on your repairs with Cheap Repair!"
keywords: "Cheap Repair Ottawa, Affordable Appliance Repair, Ottawa Appliance Services, Budget Appliance Fix Ottawa, Ottawa Home Appliance Repair, Low-Cost Appliance Repair, Ottawa Appliance Diagnostics, Economical Repair Services Ottawa, Ottawa Appliance Maintenance, Discount Appliance Repair Ottawa, Ottawa Appliance Technicians, Ottawa Refrigerator Repair, Budget-Friendly Oven Repair Ottawa, Ottawa Dishwasher Repair Service, Affordable Washer Repair Ottawa, Dryer Repair Ottawa, Ottawa Kitchen Appliance Repair, Cheap Appliance Parts Ottawa, Ottawa Major Appliance Repair, Best Price Appliance Repair Ottawa"
skills: " Cheap - Fast - Reliable "
meta_author: Repair Cheap

# Google webmaster tools
google_verify: google-site-verification=0U1LlD3LB__ky1VPD9mQVpmFkJDMgtbmrfWSiaacO8k

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: CheapRepair
  location: Location
  social: Our Social Media
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: instagram
    url: 
  - title: youtube
    url: 
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Ottawa, ON
  - line: Canada

# Credits content
credits: 'Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
